### ISSUE TITLE
Getting undefined release version in GitHub Action running Ubuntu

### ISSUE THREAD

**Issue by fwal** [retrohacker/getos#104]
Hi!

I'm having trouble getting getos to work in a GitHub action.
It have been working in the past (was some time ago since I checked) but now the `release` is undefined. (The result is `{"os":"linux","dist":"Ubuntu"}`)

Got the following from `/etc/lsb-release`:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
```

Also checked `/etc/os-release`:
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by retrohacker** [comment]
Heya @fwal, thanks for the report.

This is the logic we use for parsing Ubuntu's lsb-release file: https://github.com/retrohacker/getos/blob/master/logic/ubuntu.js

**Comment by fwal** [comment]
Yeah I tested adding the content of my `/etc/lab-release` to the tests an that worked so chances are that there’s something else in play here or that I messed something up. I’ll see what I can find...

**Comment by fwal** [comment]
So I tried running test.js in a simple GitHub Action workflow and it worked perfectly so this is most likely an error in my implementation and/or TypeScript. Closing this but will add any additional findings. 👍

**Comment by retrohacker** [comment]
Thanks for the update! Interested to hear what you find, may end up needing to update our repo or project to support GitHub actions.

**Comment by fwal** [comment]
After some testing It looks like it's a compatibility issue with getos and [@zeit/ncc](https://github.com/zeit/ncc) that I use for packing. Everything works fine until I pack the source using ncc:

```js
// test.js
const getos = require('getos')

getos((_, os) => {
  console.log(`Got os: ${JSON.stringify(os)}`)
})
```

```sh
> node test.js
# Got os: {"os":"linux","dist":"Ubuntu","codename":"bionic","release":"18.04"}
```

```sh
> ncc build test.js
> node dist/index.js
# Got os: {"os":"linux","dist":"Ubuntu"}
```

**Comment by fwal** [comment]
Notice the following caveat note about ncc:
> Files / assets are relocated based on a [static evaluator](https://github.com/zeit/webpack-asset-relocator-loader#how-it-works). Dynamic non-statically analyzable asset loads may not work out correctly

**Comment by retrohacker** [comment]
Ahhh! That makes sense, I spent some time debugging a similar thing on a SSR app today :sweat_smile: 

Thanks for following up!

**Comment by fwal** [comment]
No problem! Would you like me to create a seperate issue about this?

**Comment by fwal** [comment]
Found a solution so made a PR instead 😉
