### ISSUE TITLE
What is the license? 

### ISSUE THREAD

**Issue by SofianHn** [retrohacker/getos#31]
I am confused what is the license for this module, in package.json it says ISC but in the readme it says MIT. 

Usually adding a LICENSE file to the repo is the standard, it will be great if you can do that so I can use your module.

**Comment by retrohacker** [comment]
It is MIT. Updating where necessary.

**Comment by SofianHn** [comment]
:+1:

**Comment by retrohacker** [comment]
Shipped in 2.6.2, thanks!
