### ISSUE TITLE
Failed to loads a custom logic module in packaged project

### ISSUE THREAD

**Issue by nva** [retrohacker/getos#64]
I have packaged my application with https://github.com/zeit/pkg and find that custom logic for detection of linux distributive version cannot be loaded because have incorrect path (https://github.com/zeit/pkg#snapshot-filesystem)

It is possible to replace this path from `try { require('./logic/' + name + '.js')(os, file, cb) } catch (e) { cb(null, os) }` to `try { require(__dirname + '/logic/' + name + '.js')(os, file, cb) } catch (e) { cb(null, os) }`

**Comment by akuznetsov-gridgain** [comment]
+1

**Comment by retrohacker** [comment]
Landed in 84d7b0f8332f5191e7270171212797ebb9227dc3
