### ISSUE TITLE
recognize NixOS

### ISSUE THREAD

**Issue by flosse** [retrohacker/getos#65]
...this would also fix https://github.com/lord/wargo/issues/6# :)

**Comment by retrohacker** [comment]
Hey @flosse,

I don't have a NixOS system to test. What we would need from you to support this:

* The contents and name of your `/etc/*-release` file
* The output of `lsb_release -a`

Bonus points if you submit a PR!

**Comment by retrohacker** [comment]
This should be resolved in 3.1.1
