### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by goldingdamien** [retrohacker/getos#74]
I tried using Windows 10 Pro on a 64 bit machine.
{"os": "win32"} was returned.
Looking in the README.md and other files, it is not obvious if Windows is and/or will be supported.
If Windows is to be supported please fix the response above and state support for Windows, if not please state which OS range this is for. Regards.

**Comment by retrohacker** [comment]
Hi, this module is explicitly for Linux distributions as stated in the readme.

For windows and Mac, I simply pass through the value Node.js provides.
