### ISSUE TITLE
Unable to bundle getos using webpack

### ISSUE THREAD

**Issue by DonJayamanne** [retrohacker/getos#78]
Thanks for this awesome package.
Currently we're using it in our [Python Extension](https://github.com/Microsoft/vscode-python) for [VS Code](https://code.visualstudio.com/).

The following line of code doesn't make it easy to bundle `getos` using `webpack`.
https://github.com/retrohacker/getos/blob/a536ba7cee90ff598c1712764617c7615305d482/index.js#L124

The simple fix is to remove `__dirname`, that's quite unnecessary, as `resolve` will start from the current directory when using relative paths as follows `require('./local/xyz.js')`.

For now we've crated a separate webpack loader that makes this change to allow bundling this.

I'm hoping we can remove `__dirname` and just use `var logic = './logic/' + name + '.js';` instead.

**Comment by retrohacker** [comment]
Thank you for the thoughtful issue and PR :heart:

**Comment by retrohacker** [comment]
Released as v3.1.1

**Comment by DonJayamanne** [comment]
Oh, I thought I'd have time to fix it. Anyways
