### ISSUE TITLE
Support Release version in Linux Mint

### ISSUE THREAD

**Issue by franciscosucre** [retrohacker/getos#90]
Currently from Linux Mint 19, if i use getos it returns the following output:

```json
{ "os": "linux", "dist": "Linux Mint" }
```

I would like the library to also return the release number, if it is possible. Thanks!

**Comment by retrohacker** [comment]
Hey @franciscosucre,

Looks like mint may have changed it's file format. Today we use Ubuntu's format to parse Mint's file (https://github.com/retrohacker/getos/blob/master/logic/ubuntu.js).

Would be happy to accept a PR for this if we can keep backwards compatibility.

**Comment by hasezoey** [comment]
i know why i didnt work, i made an PR #98 that fixes it

Reason was because npm dosnt create symlinks, so mint didnt got resolved to ubuntu

**Comment by retrohacker** [comment]
Awesome, thanks @hasezoey! This went out in 3.1.3 today!
